{% set name = "qibocal" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/qiboteam/qibocal/archive/v{{ version }}.tar.gz
  sha256: c15a202af06d60c97745f7e16f269c99910d6301fe5422356ddc101c86484299

build:
  entry_points:
    - qq = qibocal:command
    - qq-compare = qibocal:compare
    - qq-live = qibocal:live_plot
    - qq-upload = qibocal:upload
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8
    - qibolab >=0.0.3
    - qibo >=0.1.9
    - pandas >=1.4.3
    - pint-pandas >=0.3
    - dash >=2.6.0
    - lmfit >=1.0.3
    - networkx >=3.0
    - pydantic >=1.10.5
    - pint >=0.20.1,<0.21

test:
  imports:
    - qibocal

about:
  home: https://github.com/qiboteam/qibocal/
  summary: Quantum calibration, characterization and validation with Qibo
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - scarrazza
