{% set name = "qibocal" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/qiboteam/qibocal/archive/v{{ version }}.tar.gz
  sha256: 878f575f1847006d4d4012fe4854fa9205dafe36f775a5a9f94d5eacf62feb5a

build:
  entry_points:
    - qq = qibocal:command
    - qq-compare = qibocal:compare
    - qq-live = qibocal:live_plot
    - qq-upload = qibocal:upload
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8
    - qibolab >=0.0.1
    - qibo >=0.1.9
    - pandas >=1.4.3
    - pint-pandas >=0.3
    - dash >=2.6.0
    - lmfit >=1.0.3

test:
  imports:
    - qibocal

about:
  home: https://github.com/qiboteam/qibocal/
  summary: 'Quantum calibration, characterization and validation with Qibo'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - scarrazza
