{% set name = "qibocal" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/qiboteam/qibocal/archive/v{{ version }}.tar.gz
  sha256: d7a61b6051f790ff6493bd1eaa25a169456656307e6436ce1839d9f41d802b32

build:
  entry_points:
    - qq = qibocal:command
    - qq-compare = qibocal:compare
    - qq-live = qibocal:live_plot
    - qq-upload = qibocal:upload
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9,<3.12
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.9,<3.12
    - qibolab >=0.1.0
    - qibo >=0.2.0
    - numpy >=1.24.0
    - scipy >=1.10.1
    - pandas >=1.4.3
    - networkx >=3.0
    - pydantic >=1.10.5
    - click >=8.1.3
    - jinja2 >=3.1.2
    - plotly >=5.15.0
    - dash >=2.6.0
    - lmfit >=1.0.3
    - skops >=0.6.0
    - scikit-learn >=1.2.1
    - pyyaml >=6.0
    - numba >=0.57.1
    - setuptools >=67.8.0

test:
  imports:
    - qibocal

about:
  home: https://github.com/qiboteam/qibocal/
  summary: Quantum calibration, characterization and validation with Qibo
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - scarrazza
